version: "3"
services:
  server:
    build:
      context: server
      dockerfile: Dockerfile
    container_name: video_server
    ports:
      - 8000:8000
    command: python3 manage.py runserver 0.0.0.0:8000
    depends_on:
      - db
  db:
    image: postgres:14.1-alpine
    container_name: video_db
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: video_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - data:/var/lib/postgresql/data
volumes:
  data: