version: "3"
services:
  db:
    image: postgres:14.1-alpine
    container_name: video_db
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: video_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - data:/var/lib/postgresql/data
volumes:
  data: